# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'baosteelSubUi副本.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1151, 878)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem1, 1, 0, 1, 1)
        self.appTitle = QtWidgets.QLabel(self.centralwidget)
        self.appTitle.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.appTitle.setFont(font)
        self.appTitle.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.appTitle.setAcceptDrops(False)
        self.appTitle.setScaledContents(True)
        self.appTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.appTitle.setObjectName("appTitle")
        self.gridLayout_9.addWidget(self.appTitle, 0, 0, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dataSearch = QtWidgets.QPushButton(self.groupBox)
        self.dataSearch.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.dataSearch.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("BaoSteel/icons/数据查询.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dataSearch.setIcon(icon)
        self.dataSearch.setCheckable(False)
        self.dataSearch.setAutoRepeat(False)
        self.dataSearch.setAutoExclusive(False)
        self.dataSearch.setAutoDefault(False)
        self.dataSearch.setObjectName("dataSearch")
        self.verticalLayout_2.addWidget(self.dataSearch)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem2)
        self.tempPred = QtWidgets.QPushButton(self.groupBox)
        self.tempPred.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.tempPred.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("BaoSteel/icons/处理预测.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tempPred.setIcon(icon1)
        self.tempPred.setObjectName("tempPred")
        self.verticalLayout_2.addWidget(self.tempPred)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem3)
        self.classDis = QtWidgets.QPushButton(self.groupBox)
        self.classDis.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.classDis.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("BaoSteel/icons/班组对比.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.classDis.setIcon(icon2)
        self.classDis.setObjectName("classDis")
        self.verticalLayout_2.addWidget(self.classDis)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_22.addWidget(self.groupBox)
        self.DataSearchWidget = QtWidgets.QStackedWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.DataSearchWidget.setFont(font)
        self.DataSearchWidget.setObjectName("DataSearchWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.page)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_6.addWidget(self.comboBox)
        self.gridLayout.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_3 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_23.addWidget(self.label_3)
        self.dateEdit = QtWidgets.QDateEdit(self.page)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_23.addWidget(self.dateEdit)
        self.line = QtWidgets.QFrame(self.page)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_23.addWidget(self.line)
        self.gridLayout.addLayout(self.horizontalLayout_23, 4, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.pushButton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("BaoSteel/icons/清空.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.page)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_7.addWidget(self.comboBox_2)
        self.gridLayout.addLayout(self.horizontalLayout_7, 3, 1, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.page)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.tableView_2 = QtWidgets.QTableView(self.page)
        self.tableView_2.setObjectName("tableView_2")
        self.gridLayout.addWidget(self.tableView_2, 5, 0, 1, 4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(238, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 3, 1, 1)
        self.sqlConnect = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sqlConnect.sizePolicy().hasHeightForWidth())
        self.sqlConnect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.sqlConnect.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("BaoSteel/icons/数据库连接.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sqlConnect.setIcon(icon4)
        self.sqlConnect.setObjectName("sqlConnect")
        self.gridLayout.addWidget(self.sqlConnect, 3, 3, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_5.addWidget(self.lineEdit_5)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.page)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout.addWidget(self.dateEdit_2, 4, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.DataSearchWidget.addWidget(self.page)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_4)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("BaoSteel/icons/计算变量.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon5)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_17.addWidget(self.pushButton_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem5)
        self.pushButton_10 = QtWidgets.QPushButton(self.page_4)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.pushButton_10.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("BaoSteel/icons/导入模型.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon6)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_17.addWidget(self.pushButton_10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(20)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem6)
        self.label_13 = QtWidgets.QLabel(self.page_4)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)
        self.comboBox_5 = QtWidgets.QComboBox(self.page_4)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.horizontalLayout_16.addWidget(self.comboBox_5)
        self.label_12 = QtWidgets.QLabel(self.page_4)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_16.addWidget(self.label_12)
        self.spinBox = QtWidgets.QSpinBox(self.page_4)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_16.addWidget(self.spinBox)
        self.pushButton_6 = QtWidgets.QPushButton(self.page_4)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("BaoSteel/icons/开始预测.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon7)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_16.addWidget(self.pushButton_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.label_26 = QtWidgets.QLabel(self.page_4)
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.verticalLayout_8.addWidget(self.label_26)
        self.tableView_3 = QtWidgets.QTableView(self.page_4)
        self.tableView_3.setObjectName("tableView_3")
        self.verticalLayout_8.addWidget(self.tableView_3)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 1)
        self.verticalLayout_8.setStretch(2, 7)
        self.gridLayout_7.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.DataSearchWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(20)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_25 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_19.addWidget(self.label_25)
        self.comboBox_17 = QtWidgets.QComboBox(self.page_5)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.comboBox_17.setFont(font)
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.horizontalLayout_19.addWidget(self.comboBox_17)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_19)
        self.pushButton_2 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_20.addWidget(self.pushButton_2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem7)
        self.verticalLayout_12.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(10)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_14 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_18.addWidget(self.label_14)
        self.comboBox_6 = QtWidgets.QComboBox(self.page_5)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.horizontalLayout_18.addWidget(self.comboBox_6)
        self.comboBox_7 = QtWidgets.QComboBox(self.page_5)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.horizontalLayout_18.addWidget(self.comboBox_7)
        self.pushButton_11 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_18.addWidget(self.pushButton_11)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem8)
        self.pushButton_7 = QtWidgets.QPushButton(self.page_5)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("BaoSteel/icons/下一页 .ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon8)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_18.addWidget(self.pushButton_7)
        self.verticalLayout_12.addLayout(self.horizontalLayout_18)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.disLabel = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.disLabel.sizePolicy().hasHeightForWidth())
        self.disLabel.setSizePolicy(sizePolicy)
        self.disLabel.setMaximumSize(QtCore.QSize(800, 450))
        self.disLabel.setText("")
        self.disLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.disLabel.setObjectName("disLabel")
        self.verticalLayout_9.addWidget(self.disLabel)
        self.disLabel_2 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.disLabel_2.sizePolicy().hasHeightForWidth())
        self.disLabel_2.setSizePolicy(sizePolicy)
        self.disLabel_2.setMaximumSize(QtCore.QSize(800, 450))
        self.disLabel_2.setText("")
        self.disLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.disLabel_2.setObjectName("disLabel_2")
        self.verticalLayout_9.addWidget(self.disLabel_2)
        self.verticalLayout_12.addLayout(self.verticalLayout_9)
        self.verticalLayout_12.setStretch(0, 1)
        self.verticalLayout_12.setStretch(1, 1)
        self.verticalLayout_12.setStretch(2, 8)
        self.gridLayout_8.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.DataSearchWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setSpacing(10)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_11 = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_21.addWidget(self.label_11)
        self.comboBox_4 = QtWidgets.QComboBox(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout_21.addWidget(self.comboBox_4)
        self.comboBox_8 = QtWidgets.QComboBox(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_8.sizePolicy().hasHeightForWidth())
        self.comboBox_8.setSizePolicy(sizePolicy)
        self.comboBox_8.setEditable(False)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.horizontalLayout_21.addWidget(self.comboBox_8)
        self.pushButton_8 = QtWidgets.QPushButton(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_21.addWidget(self.pushButton_8)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem9)
        self.pushButton_9 = QtWidgets.QPushButton(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("BaoSteel/icons/上一页 .ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon9)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_21.addWidget(self.pushButton_9)
        self.verticalLayout_13.addLayout(self.horizontalLayout_21)
        self.disTableView = QtWidgets.QTableView(self.page_6)
        self.disTableView.setObjectName("disTableView")
        self.verticalLayout_13.addWidget(self.disTableView)
        self.gridLayout_4.addLayout(self.verticalLayout_13, 0, 0, 1, 1)
        self.DataSearchWidget.addWidget(self.page_6)
        self.horizontalLayout_22.addWidget(self.DataSearchWidget)
        self.gridLayout_9.addLayout(self.horizontalLayout_22, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_6.setBuddy(self.lineEdit_3)
        self.label_5.setBuddy(self.lineEdit_2)
        self.label_7.setBuddy(self.lineEdit_4)
        self.label_4.setBuddy(self.lineEdit)
        self.label_8.setBuddy(self.lineEdit_5)
        self.label_13.setBuddy(self.comboBox_5)
        self.label_12.setBuddy(self.spinBox)

        self.retranslateUi(MainWindow)
        self.DataSearchWidget.setCurrentIndex(2)
        self.tempPred.clicked['bool'].connect(self.classDis.setDisabled)
        self.dataSearch.clicked['bool'].connect(self.tempPred.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.lineEdit_5)
        MainWindow.setTabOrder(self.lineEdit_5, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.lineEdit_4)
        MainWindow.setTabOrder(self.lineEdit_4, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.radioButton)
        MainWindow.setTabOrder(self.radioButton, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.tableView_2)
        MainWindow.setTabOrder(self.tableView_2, self.dataSearch)
        MainWindow.setTabOrder(self.dataSearch, self.tempPred)
        MainWindow.setTabOrder(self.tempPred, self.pushButton_6)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.appTitle.setText(_translate("MainWindow", "VD炉钢液温度预报系统"))
        self.groupBox.setTitle(_translate("MainWindow", "菜单："))
        self.dataSearch.setText(_translate("MainWindow", "数据查询"))
        self.tempPred.setText(_translate("MainWindow", "处理预测"))
        self.classDis.setText(_translate("MainWindow", "班组对比"))
        self.label.setText(_translate("MainWindow", "ST_NO："))
        self.label_6.setText(_translate("MainWindow", " 端口："))
        self.label_3.setText(_translate("MainWindow", "出钢日期:"))
        self.pushButton.setText(_translate("MainWindow", "清空"))
        self.label_5.setText(_translate("MainWindow", "用户名：  "))
        self.label_2.setText(_translate("MainWindow", "ldno："))
        self.radioButton.setText(_translate("MainWindow", "按照日期查询"))
        self.label_7.setText(_translate("MainWindow", " 密码："))
        self.label_4.setText(_translate("MainWindow", "主机名称："))
        self.sqlConnect.setText(_translate("MainWindow", "数据库连接"))
        self.label_8.setText(_translate("MainWindow", "数据库名称："))
        self.pushButton_4.setText(_translate("MainWindow", "计算相关变量"))
        self.pushButton_10.setText(_translate("MainWindow", "导入模型文件(.model)"))
        self.label_13.setText(_translate("MainWindow", "钢种："))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "普通钢"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "帘线钢"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "高合金"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "含硫含铝"))
        self.label_12.setText(_translate("MainWindow", "时间："))
        self.pushButton_6.setText(_translate("MainWindow", "开始预测"))
        self.label_25.setText(_translate("MainWindow", "时间段："))
        self.comboBox_17.setItemText(0, _translate("MainWindow", "近一个月"))
        self.comboBox_17.setItemText(1, _translate("MainWindow", "近三个月"))
        self.comboBox_17.setItemText(2, _translate("MainWindow", "近半年"))
        self.comboBox_17.setItemText(3, _translate("MainWindow", "近一年"))
        self.comboBox_17.setItemText(4, _translate("MainWindow", "全选"))
        self.pushButton_2.setText(_translate("MainWindow", "确定"))
        self.label_14.setText(_translate("MainWindow", "请选择钢种："))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "未分类"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "1.帘线钢"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "2.普通钢"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "3.高合金钢"))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "4.含硫含铝"))
        self.comboBox_6.setItemText(5, _translate("MainWindow", "5.弹簧钢"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "未分类"))
        self.pushButton_11.setText(_translate("MainWindow", "确定"))
        self.pushButton_7.setText(_translate("MainWindow", "下一页"))
        self.label_11.setText(_translate("MainWindow", "请选择钢种："))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "未分类"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "1.帘线钢"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "2.普通钢"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "3.高合金钢"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "4.含硫含铝"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "5.弹簧钢"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "未分类"))
        self.pushButton_8.setText(_translate("MainWindow", "确定"))
        self.pushButton_9.setText(_translate("MainWindow", "上一页"))
